---
# Installs Netdata via dockercontainer on a linux host

- name: configure the grafana settings
  template: 
    src=grafana.service.j2
    dest=/usr/lib/systemd/system/grafana.service
  register: grafana_systemd
  notify: restart grafana service
  tags: grafana

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: grafana_systemd.changed
  tags: grafana

- name: allow grafana through firewall
  shell: firewall-cmd --add-port=3000/tcp --permanent
  notify: firewall reload
  tags: grafana
