---
# This playbook deploys docker host utalizing centos as a backend.

- name: apply common configuration to all nodes
  hosts: docker
  remote_user: root
  roles:
    - common
    - docker
    - netdata