---
# This playbook deploys docker host utalizing centos as a backend.

- name: Install Rancher Controller
  hosts: rancher
  remote_user: root
  roles:
    - common
    - docker
    - telegraf
    - netdata
    