# Role to install and configure Apache Guacamole
---

- name: create /etc/docker/compose/guacamole directory
  file:
    path: /etc/docker/compose/guacamole
    state: directory

- name: copy dockerfile that compiles mysql 
  copy:
    src: Dockerfile
    dest: /etc/docker/compose/guacamole/Dockerfile

- name: check if init.db file exists
  stat: 
    path: /etc/docker/compose/guacamole/initdb.sql
  register: initdb_sql

- name: generate init.db from shell command
  shell:
    cmd: docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > tmp.sql; echo "USE {{ GUACAMOLE_MYSQL_DATABASE }}" | cat - tmp.sql > initdb.sql; rm -f tmp.sql;
    chdir: /etc/docker/compose/guacamole
  when: initdb_sql.stat.exists == False

- name: copy docker-compose template
  template: 
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/guacamole/docker-compose.yml
  notify: restart guacamole service

- name: copy nginx configuration
  copy: 
    src: nginx.conf
    dest: /etc/docker/compose/guacamole/nginx.conf
  notify: restart guacamole service

- name: copy systemd service file
  copy: 
    src: guacamole.service
    dest: /usr/lib/systemd/system/guacamole.service
  register: guacamole_systemd
  notify: restart guacamole service

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: guacamole_systemd.changed
  tags: netdata

- debug:
    msg: "{{ GUACAMOLE_LISTENING_PORT }}"

- name: open port on firewalld
  firewalld:
    port: "{{ GUACAMOLE_LISTENING_PORT }}/tcp"
    permanent: yes
    state: enabled
