---
# Common playbook for all centos7 servers

# install local SSH public key to remote system, next runs wont need -k
- name: update remote authorized SSH keys for future ansible runs
  authorized_key: user={{ ansible_user_id }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  ignore_errors: yes

- include: ntp.yml

- include: selinux.yml

- include: yum.yml

# will be > 0 if its on a VMware hypervisor
- name: verify if host is on vmware
  shell: dmidecode | grep -i vmware | wc -l
  register: vmware_check 

# use play if vmware is present
- include: vmtools.yml
  when: vmware_check > 1
