---
# Playbook to install and configure NTP service.

- name: ensure NTP-related packages are installed.
  package:
    name: ntp
    state: present
  tags: ntp

- name: ensure tzdata package is installed (Linux).
  package:
    name: tzdata
    state: present
  when: ansible_system == "Linux"
  tags: ntp

- name: Set timezone
  timezone:
    name: "{{ server_timezone }}"
  tags: ntp

- name: configure the ntp settings file /etc/ntp.conf and restarting ntpd service
  template: 
    src=ntp.conf.j2 
    dest=/etc/ntp.conf
  tags: ntp

- name: allow ntp through firewall
  shell: firewall-cmd --add-service=ntp --permanent
  notify: firewall reload
  tags: ntp

- name: stopping NTP in order to force an update
  service: 
    name=ntpd 
    state=stopped
  tags: ntp

- name: performing NTP sync with primary ntp server
  shell: ntpdate {{ ntpserver[0] }}
  ignore_errors: yes
  tags: ntp

- name: starting NTP service and forcing to start on reboot
  service: 
    name=ntpd 
    state=started 
    enabled=yes
  tags: ntp
