---
# Installs Netdata via dockercontainer on a linux host

- name: configure the telegraf service settings
  template: 
    src=telegraf.service.j2
    dest=/usr/lib/systemd/system/telegraf.service
  register: telegraf_systemd
  notify: restart telegraf service
  tags: telegraf

- name: create telegraf directory
  file: path=/var/docker/telegraf/ state=directory    

- name: configure the telegraf configuration file
  copy: 
    src=telegraf.conf
    dest=/var/docker/telegraf/telegraf.conf
  register: telegraf_config
  notify: restart telegraf service
  tags: telegraf

- name: force systemd to reread configs
  systemd: daemon_reload=yes
  when: telegraf_systemd.changed
  tags: telegraf
